import './globals.css';
import Sidebar from './Components/Sidebar';
import SessionProvider from './Components/SessionProvider';
import { getServerSession } from 'next-auth';
import handler from './api/auth/[...nextauth]/route';
import Login from './Components/Login';

export const metadata = {
  title: 'Chat GPT Clone',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(handler);
  console.log(session);
  return (
    <html lang='en'>
      <body>
        <SessionProvider>
          {!session ? (
            <Login />
          ) : (
            <div className='flex'>
              <Sidebar />
              {children}
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
